# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
    id: ID!
    name: String!
    email: String!
    img_user: String!
    password: String!
    role: String!
    rating: Int!
    balance: Int!
    created_at: String
}

type Order {
    id: ID!
    buyer_id: ID!
    status: Int!
    total_amout: Int!
    order_buy: Int!
}
type Product {
    id: ID!
    sellerID: ID!
    categoryID: Int!
    name: String!
    description: String!
    price: Int!
    rating: Float!
    tags: [String]!
    create_at: String!
}
type OrderItem {
    id: ID!
    orderID: ID!
    productID: ID!
    price_at_purchase: Int!
}

type Query {
    getUser(name: String, email: String, id: ID): [User]
    getProduct(name: String, id: ID, sellerID: ID): [Product]
    getOrder(id: ID, buyer_id: ID, total_amout: Int, order_buy: Int): [Order]
}

type Mutation {
    setUser(
        name: String!
        email: String!
        img_user: String!
        password: String!
    ): User
    setProduct(
        sellerID: ID!
        categoryID: Int!
        name: String!
        description: String!
        price: Int!
        rating: Float!
        tags: [String]!
    ): Product
}
