# GraphQL schema example
#
# https://gqlgen.com/getting-started/

enum StatusOrder {
    pending
    processing
    shipped
    delivered
}

type User {
    id: ID!
    name: String!
    email: String!
    img_user: String!
    role: String!
    rating: Int
    balance: Int
}

type Order {
    id: ID!
    buyer_id: ID!
    status: StatusOrder!
    total_amout: Int
    data_buy: Int
}
type Product {
    id: ID!
    sellerID: ID!
    categoryID: Int!
    name: String!
    description: String!
    price: Int!
    rating: Float!
    tags: [String!]!
    createdAt: String!
}
type OrderItem {
    id: ID!
    orderID: ID!
    productID: ID!
    priceAtPurchase: Int!
}
type Query {
    todos: [Todo!]!
}

input NewTodo {
    text: String!
    userId: String!
}

type Mutation {
    createTodo(input: NewTodo!): Todo!
}
