package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/rrrr22wwww.com/cloudflow/graph/model"
)

type Param struct {
	Column string
	Value  *string
}

// SetUser is the resolver for the setUser field.
func (r *mutationResolver) SetUser(ctx context.Context, name string, email string, imgUser string, password string) (*model.User, error) {
	user := &model.User{}

	err := r.DB.QueryRowContext(ctx,
		`INSERT INTO users (id, name, email, img_user, password, role, rating, balance)
           VALUES (gen_random_uuid(), $1, $2, $3, $4, 'User', 0, 0)
           RETURNING id, name, email, img_user, role, rating, balance`,
		name, email, imgUser, password,
	).Scan(&user.ID, &user.Name, &user.Email, &user.ImgUser, &user.Role, &user.Rating, &user.Balance)

	if err != nil {
		return nil, err
	}
	return user, nil
}

// SetProduct is the resolver for the setProduct field.
func (r *mutationResolver) SetProduct(ctx context.Context, sellerID string, categoryID int32, name string, description string, price int32, rating float64, tags []*string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: SetProduct - setProduct"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, name *string, email *string, id *string) (*model.User, error) {
	user := &model.User{}

	err := r.DB.QueryRowContext(ctx,
		`SELECT id, name, email, img_user, role, rating, balance
           FROM users WHERE id = $1`,
		id,
	).Scan(&user.ID, &user.Name, &user.Email, &user.ImgUser, &user.Role, &user.Rating, &user.Balance)

	if err != nil {
		return nil, err
	}
	return user, nil
}

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, name *string, id *string, sellerID *string) (*model.Product, error) {
	product := &model.Product{}
	args := []any{}
	params := []Param{
		{"name", name},
		{"id", id},
		{"seller_id", sellerID},
	}

	query := "SELECT id, seller_id, name, description, price, rating, tags, created_at FROM products WHERE 1=1"
	argIdx := 1
	for _, p := range params {
		if p.Value != nil {
			query += fmt.Sprintf(" AND %s = $%d", p.Value, argIdx)
			args = append(args, *p.Value)
			argIdx++
		}
	}
	err := r.DB.QueryRowContext(ctx, query, args...).Scan(
		&product.ID, &product.SellerID, &product.Name, &product.Description,
		&product.Price, &product.Rating, &product.Tags, &product.CreateAt)
	if err != nil {
		return nil, err
	}
	return product, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
