// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Category struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	ParentID *int32 `json:"parent_id,omitempty"`
}

type EmailLoginCodePayload struct {
	ChallengeID string `json:"challenge_id"`
	Email       string `json:"email"`
	ExpiresIn   int32  `json:"expires_in"`
}

type Mutation struct {
}

type Order struct {
	ID          string  `json:"id"`
	BuyerID     string  `json:"buyer_id"`
	Status      string  `json:"status"`
	TotalAmount float64 `json:"total_amount"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
}

type OrderItem struct {
	ID              string `json:"id"`
	OrderID         string `json:"orderID"`
	ProductID       string `json:"productID"`
	PriceAtPurchase int32  `json:"price_at_purchase"`
}

type Product struct {
	ID           string    `json:"id"`
	SellerID     string    `json:"seller_id"`
	CategoryID   *int32    `json:"category_id,omitempty"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Price        float64   `json:"price"`
	Rating       *int32    `json:"rating,omitempty"`
	Status       *string   `json:"status,omitempty"`
	PreviewImage *string   `json:"preview_image,omitempty"`
	Tags         []*string `json:"tags,omitempty"`
	CreatedAt    string    `json:"created_at"`
	UpdatedAt    string    `json:"updated_at"`
}

type PurchasePayload struct {
	Order   *Order   `json:"order"`
	Product *Product `json:"product"`
	Buyer   *User    `json:"buyer"`
}

type Query struct {
}

type SellerReview struct {
	ID        int32   `json:"id"`
	SellerID  string  `json:"seller_id"`
	BuyerID   string  `json:"buyer_id"`
	ProductID string  `json:"product_id"`
	Rating    int32   `json:"rating"`
	Comment   *string `json:"comment,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type ServerAccess struct {
	ProductID       string  `json:"product_id"`
	IPAddress       string  `json:"ip_address"`
	SSHUsername     string  `json:"ssh_username"`
	SSHPassword     *string `json:"ssh_password,omitempty"`
	SSHPrivateKey   *string `json:"ssh_private_key,omitempty"`
	Port            *int32  `json:"port,omitempty"`
	ConnectionNotes *string `json:"connection_notes,omitempty"`
	CreatedAt       *string `json:"created_at,omitempty"`
	UpdatedAt       *string `json:"updated_at,omitempty"`
}

type User struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Email     string   `json:"email"`
	ImgUser   *string  `json:"img_user,omitempty"`
	Role      *string  `json:"role,omitempty"`
	Rating    *int32   `json:"rating,omitempty"`
	Balance   *float64 `json:"balance,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}
