// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	ParentID *int32 `json:"parent_id,omitempty"`
}

type Mutation struct {
}

type Order struct {
	ID          string  `json:"id"`
	BuyerID     string  `json:"buyer_id"`
	Status      string  `json:"status"`
	TotalAmount float64 `json:"total_amount"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
}

type OrderItem struct {
	ID              string `json:"id"`
	OrderID         string `json:"orderID"`
	ProductID       string `json:"productID"`
	PriceAtPurchase int32  `json:"price_at_purchase"`
}

type Product struct {
	ID          string    `json:"id"`
	SellerID    string    `json:"seller_id"`
	CategoryID  *int32    `json:"category_id,omitempty"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Rating      *int32    `json:"rating,omitempty"`
	Status      *string   `json:"status,omitempty"`
	Tags        []*string `json:"tags,omitempty"`
	CreatedAt   string    `json:"created_at"`
	UpdatedAt   string    `json:"updated_at"`
}

type Query struct {
}

type User struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Email     string   `json:"email"`
	ImgUser   *string  `json:"img_user,omitempty"`
	Role      *string  `json:"role,omitempty"`
	Rating    *int32   `json:"rating,omitempty"`
	Balance   *float64 `json:"balance,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}
